# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Create NuGet Package

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack src/CLI.IPC.csproj /p:ContinuousIntegrationBuild=true --output .
    - name: Upload *.nupkg
      uses: actions/upload-artifact@v4
      with:
        name: NuGet Package
        path: |
          **/*.nupkg
          **/*.snupkg
